-- Listado de jugadores que al menos han jugado una partida
SELECT DISTINCT PLAYERS.ID, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID;

-- Listado de jugadores que no han jugado una partida
SELECT PLAYERS.ID, PLAYERS.NAME
FROM PLAYERS
LEFT JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
WHERE PLAYERS_TURNS.ID IS NULL;

-- Listado de jugadores que al menos han ganado una partida
SELECT DISTINCT PLAYERS.ID, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
WHERE PLAYERS_TURNS.IS_WINNER = 1;

SELECT ID, NAME
FROM PLAYERS
WHERE WINNINGS > 0;

-- Listado de Jugadores que no han perdido una partida
SELECT ID, NAME
FROM PLAYERS
WHERE LOSSES = 0;

-- Top 3 de los peores jugadores (partidas perdidas)
SELECT ID, NAME, LOSSES
FROM PLAYERS
ORDER BY LOSSES DESC
FETCH NEXT 3 ROWS ONLY;

-- Top 3 de los mejores jugadores (partidas ganadas)
SELECT ID, NAME, WINNINGS
FROM PLAYERS
ORDER BY WINNINGS DESC
FETCH NEXT 3 ROWS ONLY;

-- Top 3 de los mejores jugadores hangman
SELECT COUNT(PLAYERS_TURNS.ID) AS HANGMAN_WINNINGS, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
INNER JOIN TURNS
ON TURNS.ID = PLAYERS_TURNS.TURNS_ID
WHERE GAMES_ID = 002 AND PLAYERS_TURNS.IS_WINNER = 1
GROUP BY PLAYERS_TURNS.PLAYERS_ID, PLAYERS.NAME
ORDER BY HANGMAN_WINNINGS DESC
FETCH NEXT 3 ROWS ONLY;

-- Top 3 de los mejores jugadores ttt
SELECT COUNT(PLAYERS_TURNS.ID) AS TICTACTOE_WINNINGS, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
INNER JOIN TURNS
ON TURNS.ID = PLAYERS_TURNS.TURNS_ID
WHERE GAMES_ID = 001 AND PLAYERS_TURNS.IS_WINNER = 1
GROUP BY PLAYERS_TURNS.PLAYERS_ID, PLAYERS.NAME
ORDER BY TICTACTOE_WINNINGS DESC
FETCH NEXT 3 ROWS ONLY;

-- Top 3 de los peores jugadores hangman
SELECT COUNT(PLAYERS_TURNS.ID) AS HANGMAN_LOSSES, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
INNER JOIN TURNS
ON TURNS.ID = PLAYERS_TURNS.TURNS_ID
WHERE GAMES_ID = 002 AND PLAYERS_TURNS.IS_WINNER = 0
GROUP BY PLAYERS_TURNS.PLAYERS_ID, PLAYERS.NAME
ORDER BY HANGMAN_LOSSES DESC
FETCH NEXT 3 ROWS ONLY;

-- Top 3 de los peores jugadores ttt
SELECT COUNT(PLAYERS_TURNS.ID) AS TICTACTOE_LOSSES, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
INNER JOIN TURNS
ON TURNS.ID = PLAYERS_TURNS.TURNS_ID
WHERE GAMES_ID = 001 AND PLAYERS_TURNS.IS_WINNER = 0
GROUP BY PLAYERS_TURNS.PLAYERS_ID, PLAYERS.NAME
ORDER BY TICTACTOE_LOSSES DESC
FETCH NEXT 3 ROWS ONLY;

-- Jugador de TTT con menos tiros para ganar
SELECT MIN(PLAYERS_TURNS.ACTIONS_NUMBER) AS ACTIONS, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
INNER JOIN TURNS
ON TURNS.ID = PLAYERS_TURNS.TURNS_ID
WHERE GAMES_ID = 001 
GROUP BY PLAYERS.ID, PLAYERS.NAME
ORDER BY ACTIONS ASC
FETCH NEXT 1 ROWS ONLY;

-- Jugador de Hangman con menos intentos al ganar
SELECT MIN(PLAYERS_TURNS.ACTIONS_NUMBER) AS ACTIONS, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
INNER JOIN TURNS
ON TURNS.ID = PLAYERS_TURNS.TURNS_ID
WHERE GAMES_ID = 002 
GROUP BY PLAYERS.ID, PLAYERS.NAME
ORDER BY ACTIONS ASC
FETCH NEXT 1 ROWS ONLY;

-- Jugador de TTT con más tiros para ganar
SELECT MAX(PLAYERS_TURNS.ACTIONS_NUMBER) AS ACTIONS, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
INNER JOIN TURNS
ON TURNS.ID = PLAYERS_TURNS.TURNS_ID
WHERE GAMES_ID = 001 
GROUP BY PLAYERS.ID, PLAYERS.NAME
ORDER BY ACTIONS DESC
FETCH NEXT 1 ROWS ONLY;

-- Jugador de Hangman con más intentos para ganar
SELECT MAX(PLAYERS_TURNS.ACTIONS_NUMBER) AS ACTIONS, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
INNER JOIN TURNS
ON TURNS.ID = PLAYERS_TURNS.TURNS_ID
WHERE GAMES_ID = 002 AND PLAYERS_TURNS.ACTIONS_NUMBER IS NOT NULL
GROUP BY PLAYERS.ID, PLAYERS.NAME
ORDER BY ACTIONS DESC
FETCH NEXT 1 ROWS ONLY;

-- Promedio de tiros en TTT para ganar una partida ( partidas empatadas y en progreso no cuentan)
SELECT AVG(PLAYERS_TURNS.ACTIONS_NUMBER) AS AVERAGE
FROM TURNS
INNER JOIN PLAYERS_TURNS
ON TURNS.ID = PLAYERS_TURNS.TURNS_ID
WHERE GAMES_ID = 001 AND IS_FINISHED = 1;

SELECT * FROM PLAYERS;
SELECT * FROM PLAYERS_TURNS;

-- Promedio del tamaño de palabras utilizadas en Hangman

-- Mostrar Listado de los jugadores de Hangman y establecer si son mejores como guiver o guesser

-- Mostrar listado de los jugadores de TTT y mostrar si son mejores con las X o las O
